go-zeromq/zmq4

- example/psenvpub.go
- example/psenvsub.go
- example/rrclient.go
- example/rrworker.go
- example/rtdealer.go
Done mechanically with:
```
$> sed -i -e 's|//+build|// +build|' $(grep -l '//+build' -R|grep \.go$)
```
> all: conform build tag comment to Go convention

- cxx_zmq4_compat.go
- dealer.go
- pair.go
- pub.go
- pull.go
- push.go
- rep.go
- req.go
- router.go
- socket.go
- sub.go
- xpub.go
- xsub.go
- zmq4.go
It's sometimes useful to listen to an ephemeral port assigned by the kernel, rather than a hardcoded one, for, for example, service discovery.
I've added a new method to the `Socket` interface to facilitate this which makes the following possible:
```go
pub = zmq4.NewPub(context.Background())
_ = pub.Listen("tcp://0.0.0.0:0")
addr := pub.Addr().String()
svcdisco.Register(addr)
```
> zmq4: provide Socket.Addr() interface

- conn.go
- msgio.go
- pub.go
- router.go
- socket.go
- zmq4_pubsub_test.go
Furthermore; do not return errors when publishing writes on closed connections.
Fixes go-zeromq/zmq4#39.
Basically,  rpool and wpool's add(rm)Conn methods were refactored to accept `*zmq4.Conn` so that `zmq4.socket` to be able to notify lower layers of closed connections.
All IO operations in `zmq4.Conn` are now guarded by a check to detect stale/closed connections. Once a closed connection is detected, the higher layer can then be notified via a configured close notification callback.
> zmq4: remove closed connections from pools

- socket.go
The data race manifests when the socket context's deadline has passed.
Fixes go-zeromq/zmq#50
> zmq4: Fix data race in socket.Close

- conn.go
- socket.go
- zmq4_pubsub_test.go
Fixes the following bugs:
* Race condition on `socket.conns` when calling `Socket.Close` and the connReaper.
* Deadlocks when sending on `socket.closedConns` for a dial-only socket. The send blocks indefinitely because the connReaper wasn't  available to receive the closed connections.
* When checking for IO errors in conn.go, `io.EOF` wasn't being considered. This caused a connection to a dead PUB/PUSH/etc to be extant indefinitely.
`TestPubSubDeadPub` tests for the scenarios above.
> zmq4: fix data races and deadlocks upon closed dial peers

- .travis.yml
- protocol.go
- protocol_test.go
> zmq4: extend ZMTP greeting tests for various version cases

- socket.go
- zmq4_pair_test.go
- zmq4_pubsub_test.go
- zmq4_pushpull_test.go
- zmq4_reqrep_test.go
- zmq4_routerdealer_test.go
- zmq4_xpubsub_test.go
This CL makes sockets that are closed before anybody else had time to
connect a non failing operation.
Fixes go-zeromq/zmq4#57.
> zmq4: closing a socket with no peer is not an error

- conn.go
- socket.go
- socket_test.go
> zmq4: do not panic b/c of invalid connection attempts

- socket.go
When closing a dialed ipc socket, do not remove the socket file since we are not the server. Removing the unix socket file on disk only if net.Listen was used to create the file.
> zmq4: preserve dialed ipc socket when closing

- pub.go
- socket.go
- xpub.go
- zmq4_xpubsub_test.go
I was developing a way to determine if an xpub socket had already got its list of topics from a zmq proxy and saw that this was missing. I moved the method to the socket struct so it could be used from pub and xpub sockets.
> implement Topics() interface for xpub sockets

- socket.go
The previous PR (#106) failed to unlock `reaperCond.L` when the context was done, which causes deadlocks in certain circumstances. The new structure ensures the lock is always released, while also avoiding spurious `Lock()/Unlock()` calls (note that `reaperCond.Wait()` [atomically unlocks](https://pkg.go.dev/sync@go1.15.13#Cond.Wait) before entering its wait state).
> Ensure reaperCond is unlocked when context is canceled

- msgio.go
- pub.go
- router.go
Currently `semaphore` will block a `qreader` read from exiting even when the context have been canceled. From what I can tell its purpose is to guarantee there is a connection first (from `addConn`) before the read could proceed. However, this requirement makes it hard to write unit tests that might be blocked on waiting for the context to finish.
This change adds context into the semaphore so that read can be unblocked when the context is canceled, instead of resulting in a deadlock.
> Add context to semaphore

- socket.go
- socket_test.go
- sub.go
> zmq4: resend subscriptions in socket.addConn

- options.go
- socket.go
- socket_test.go
I have not tested this yet, it's meant as discussion base for #124
> zmq4: add option for automatic reconnect

- zmq4.go
I've lost some time when trying to build a very simple pub-sub (without looking at the examples).
I called `Socket.Listen()` in my sub, and `Socket.Dial()` on my pub. It had to be reversed to work. I thought docs could clarify this.
Also, I think it a bit confusing that my publisher calls `Listen()`, as if it was listening for messages. Why was this named like this?
> Clarify docs a bit about how Listen() and Dial() translate to bind() and connect()

- .github/workflows/ci.yml
Simplified the workflow and added verifying that code is formatted with `gofmt`.
> Improve the `CI` github action

- socket.go
By default, `libzmq` implementation sends empty Identity. Also in `libzmq` implementation, when a server receives an empty Identity for Router connections, it falls back to auto generation. Otherwise, the Router socket will by large chance misbehave.
See: https://github.com/zeromq/libzmq/blob/master/src/router.cpp#L481-L487
Additionally, remove `sck.ids`, which is unused and leaks `*Conn`.
> Deal with empty Identity for ROUTER socket

- rep.go
- rep_test.go
I have found a race condition in the ctx cancellation in `repWriter`. 
Added a test which reproduces the issue with a possible fix. 
I don't quite understand why dont we use `ctx` in the  write routine, see my second commit about that.
> Fix rep cancellation

- go.mod
- go.sum
- leaks_test/reaper_leak_test.go
- reaper/reaper_test.go
- socket.go
> Fix connReaper goroutine may leak

- pub.go
Hey! I'm a fan of this library. A couple of tweaks:
- Default high-water mark:
* The HWM is currently set to zero, which allows the queue to grow infinitely - https://github.com/go-zeromq/zmq4/issues/151.
* The spec states that we ["SHOULD constrain queue sizes to a runtime-configurable limit"](https://rfc.zeromq.org/spec/29/#the-pub-socket-type). In libzmq, the [default is 1000](https://libzmq.readthedocs.io/en/latest/zmq_setsockopt.html), so that seemed like a sensible choice. Side note, there was a TODO to allow for "per subscriber hwm". The zmq docs are a bit vague in some places but it seems like it's supposed to be per-socket rather than per-subscriber.
* This allows us to use Go's buffered channels instead of `Queue`.
- Per-subscriber queues:
* Currently, the pub socket maintains a …
> added default hwm and per-subscriber queues
